/*
=============================================================
  Customer Shopping Behavior Analysis — SQL Queries
  Database : SQL Server (T-SQL)
  Tables   : customer, products, stores, marketing_campaigns
=============================================================
=============================================================
*/


-- ============================================================
-- SECTION A: Customer_enriched QUERIES 
-- ============================================================

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
    item_purchased,
    ROUND(CAST(AVG(review_rating) AS DECIMAL(5,2)), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(CAST(purchase_amount_usd AS DECIMAL(10,2))), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more?
--     Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id)                                          AS total_customers,
       ROUND(AVG(CAST(purchase_amount_usd AS DECIMAL(10,2))), 2)  AS avg_spend,
       ROUND(SUM(CAST(purchase_amount_usd AS DECIMAL(10,2))), 2)  AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
    2) AS discount_rate_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
WITH customer_segments AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1               THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10  THEN 'Returning'
               ELSE                                           'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are repeat buyers (>5 previous purchases) more likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- ============================================================
-- SECTION B:   Business Requirements Deliverables
-- ============================================================

-- Q11. Which products have a profit margin below 40% but rank in the top 10 by sales volume?
--      (Margin-squeeze alert — high volume but low profit)
WITH product_sales AS (
    SELECT item_purchased,
           COUNT(*)                    AS total_orders,
           SUM(purchase_amount_usd)    AS total_revenue,
           RANK() OVER (ORDER BY COUNT(*) DESC) AS sales_rank
    FROM customer
    GROUP BY item_purchased
)
SELECT ps.item_purchased,
       p.category,
       p.profit_margin_pct,
       ps.total_orders,
       ps.sales_rank,
       p.supplier_name
FROM product_sales ps
JOIN products p ON ps.item_purchased = p.product_name
WHERE p.profit_margin_pct < 40
  AND ps.sales_rank <= 10
ORDER BY ps.sales_rank;


-- Q12. Which products are currently below their reorder level?
--      (Inventory risk — needs restocking immediately)
SELECT p.product_id,
       p.product_name,
       p.category,
       p.stock_quantity,
       p.reorder_level,
       p.reorder_level - p.stock_quantity AS units_short,
       p.supplier_name
FROM products p
WHERE p.stock_quantity < p.reorder_level
ORDER BY units_short DESC;


-- Q13. What is the actual revenue vs estimated revenue per category?
--      (purchase_amount_usd vs selling_price * orders — reveals discount impact)
SELECT p.category,
       COUNT(c.customer_id)              AS total_orders,
       SUM(c.purchase_amount_usd)        AS actual_revenue,
       SUM(p.selling_price_inr * 0.012)  AS estimated_revenue_usd, -- approx INR→USD
       ROUND(
           100.0 * (SUM(p.selling_price_inr * 0.012) - SUM(c.purchase_amount_usd))
           / SUM(p.selling_price_inr * 0.012),
       2)                                AS revenue_gap_pct
FROM customer c
JOIN products p ON c.item_purchased = p.product_name
GROUP BY p.category
ORDER BY revenue_gap_pct DESC;


-- Q14. Which supplier's products have the highest average customer review rating?
SELECT p.supplier_name,
       COUNT(DISTINCT p.product_name)                                    AS products_supplied,
       ROUND(AVG(CAST(c.review_rating AS DECIMAL(5,2))), 2)              AS avg_rating,
       SUM(c.purchase_amount_usd)                                        AS total_revenue
FROM customer c
JOIN products p ON c.item_purchased = p.product_name
GROUP BY p.supplier_name
ORDER BY avg_rating DESC;


-- ============================================================
-- SECTION C: Business Requirements Deliverables - Store  
-- ============================================================

-- Q15. Compare average order value across Metro, Tier-2, and Online store types.
SELECT s.city_tier,
       s.store_type,
       COUNT(c.customer_id)                                             AS total_orders,
       ROUND(AVG(CAST(c.purchase_amount_usd AS DECIMAL(10,2))), 2)     AS avg_order_value,
       SUM(c.purchase_amount_usd)                                       AS total_revenue
FROM customer c
JOIN stores s ON c.store_id = s.store_id
GROUP BY s.city_tier, s.store_type
ORDER BY avg_order_value DESC;


-- Q16. Which region generates the highest revenue, and what is its subscription rate?
SELECT s.region,
       COUNT(c.customer_id)                                              AS total_customers,
       SUM(c.purchase_amount_usd)                                        AS total_revenue,
       ROUND(
           100.0 * SUM(CASE WHEN c.subscription_status = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(c.customer_id),
       2)                                                                AS subscription_rate_pct
FROM customer c
JOIN stores s ON c.store_id = s.store_id
WHERE s.region != 'N/A'   -- exclude online
GROUP BY s.region
ORDER BY total_revenue DESC;


-- Q17. Which individual store has the highest revenue per square foot?
--      (Retail KPI — measures how efficiently floor space is monetised)
SELECT s.store_name,
       s.city,
       s.store_size_sqft,
       SUM(c.purchase_amount_usd)                                          AS total_revenue,
       ROUND(
           SUM(c.purchase_amount_usd) * 1.0 / s.store_size_sqft,
       2)                                                                  AS revenue_per_sqft
FROM customer c
JOIN stores s ON c.store_id = s.store_id
WHERE s.store_type != 'Online'   -- sqft is NULL for online stores
GROUP BY s.store_name, s.city, s.store_size_sqft
ORDER BY revenue_per_sqft DESC;


-- Q18. Online vs Offline: Compare average review rating and discount usage.
SELECT
    CASE WHEN s.store_type = 'Online' THEN 'Online' ELSE 'Offline' END AS channel,
    COUNT(c.customer_id)                                                  AS total_orders,
    ROUND(AVG(CAST(c.review_rating AS DECIMAL(5,2))), 2)                 AS avg_review_rating,
    ROUND(
        100.0 * SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(c.customer_id),
    2)                                                                    AS discount_usage_pct
FROM customer c
JOIN stores s ON c.store_id = s.store_id
GROUP BY CASE WHEN s.store_type = 'Online' THEN 'Online' ELSE 'Offline' END
ORDER BY total_orders DESC;


-- ============================================================
-- SECTION D:Business Requirements Deliverables — MARKETING CAMPAIGNS 
-- ============================================================

-- Q19. What is the ROI of each marketing campaign?
--      ROI = (Revenue Generated / Budget) — higher is better
WITH campaign_revenue AS (
    SELECT campaign_id,
           SUM(purchase_amount_usd) AS revenue_usd
    FROM customer
    WHERE campaign_id IS NOT NULL
    GROUP BY campaign_id
)
SELECT m.campaign_id,
       m.campaign_name,
       m.season,
       m.channel,
       m.budget_inr_lakhs,
       cr.revenue_usd                                                AS revenue_usd,
       ROUND(cr.revenue_usd / (m.budget_inr_lakhs * 1200), 2)       AS roi_ratio
       -- 1 lakh INR ≈ 1200 USD (approx conversion for analysis)
FROM marketing_campaigns m
JOIN campaign_revenue cr ON m.campaign_id = cr.campaign_id
ORDER BY roi_ratio DESC;


-- Q20. Which campaign channel (Email / SMS / Social Media) drives the most revenue?
SELECT m.channel,
       COUNT(DISTINCT c.customer_id)                                AS customers_reached,
       SUM(c.purchase_amount_usd)                                   AS total_revenue,
       ROUND(AVG(CAST(c.purchase_amount_usd AS DECIMAL(10,2))), 2) AS avg_order_value
FROM customer c
JOIN marketing_campaigns m ON c.campaign_id = m.campaign_id
GROUP BY m.channel
ORDER BY total_revenue DESC;


-- Q21. Do customers acquired via Festive campaigns have higher repeat purchase rates?
--      (Campaign quality metric — not just conversion but long-term loyalty)
SELECT
    CASE
        WHEN m.season = 'Festive'   THEN 'Festive Campaign'
        WHEN c.campaign_id IS NULL  THEN 'Organic (No Campaign)'
        ELSE 'Non-Festive Campaign'
    END                                                             AS acquisition_type,
    COUNT(c.customer_id)                                            AS total_customers,
    ROUND(AVG(CAST(c.previous_purchases AS DECIMAL(10,2))), 2)     AS avg_previous_purchases,
    ROUND(AVG(CAST(c.purchase_amount_usd AS DECIMAL(10,2))), 2)    AS avg_order_value
FROM customer c
LEFT JOIN marketing_campaigns m ON c.campaign_id = m.campaign_id
GROUP BY
    CASE
        WHEN m.season = 'Festive'   THEN 'Festive Campaign'
        WHEN c.campaign_id IS NULL  THEN 'Organic (No Campaign)'
        ELSE 'Non-Festive Campaign'
    END
ORDER BY avg_previous_purchases DESC;


-- Q22. Which campaign had the highest discount uptake rate?
--      (What % of purchases under this campaign actually used the discount?)
SELECT m.campaign_name,
       m.season,
       m.discount_offered_pct,
       COUNT(c.customer_id)                                         AS total_purchases,
       SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
       ROUND(
           100.0 * SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(c.customer_id),
       2)                                                           AS discount_uptake_pct
FROM customer c
JOIN marketing_campaigns m ON c.campaign_id = m.campaign_id
GROUP BY m.campaign_name, m.season, m.discount_offered_pct
ORDER BY discount_uptake_pct DESC;


-- ============================================================
-- SECTION E: ADVANCED / MULTI-TABLE QUERIES Analysis
-- ============================================================

-- Q23. Full funnel view: For each campaign, show store performance breakdown.
--      (Which stores benefited most from each campaign?)
SELECT m.campaign_name,
       s.store_name,
       s.city_tier,
       COUNT(c.customer_id)       AS orders,
       SUM(c.purchase_amount_usd) AS revenue
FROM customer c
JOIN marketing_campaigns m ON c.campaign_id = m.campaign_id
JOIN stores s              ON c.store_id    = s.store_id
GROUP BY m.campaign_name, s.store_name, s.city_tier
ORDER BY m.campaign_name, revenue DESC;


-- Q24. Identify high-value loyal customers: subscribed + loyal segment + above-avg spend.
--      (Gold tier customer identification — CRM use case)
WITH loyal_subscribers AS (
    SELECT c.customer_id,
           c.age_group,
           c.gender,
           c.previous_purchases,
           c.purchase_amount_usd,
           s.city,
           s.city_tier,
           CASE
               WHEN c.previous_purchases > 10 THEN 'Loyal'
               WHEN c.previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'New'
           END AS segment
    FROM customer c
    JOIN stores s ON c.store_id = s.store_id
    WHERE c.subscription_status = 'Yes'
)
SELECT segment,
       city_tier,
       COUNT(customer_id)                                             AS customer_count,
       ROUND(AVG(CAST(purchase_amount_usd AS DECIMAL(10,2))), 2)     AS avg_spend,
       ROUND(AVG(CAST(previous_purchases  AS DECIMAL(10,2))), 2)     AS avg_purchases
FROM loyal_subscribers
GROUP BY segment, city_tier
ORDER BY avg_spend DESC;


-- Q25. Running total of revenue by store (month simulation using customer_id as proxy).
--      (Demonstrates window functions — always impressive in interviews)
WITH store_revenue AS (
    SELECT s.store_name,
           s.region,
           c.purchase_amount_usd,
           ROW_NUMBER() OVER (PARTITION BY s.store_id ORDER BY c.customer_id) AS txn_seq
    FROM customer c
    JOIN stores s ON c.store_id = s.store_id
)
SELECT store_name,
       region,
       txn_seq,
       purchase_amount_usd,
       SUM(purchase_amount_usd) OVER (
           PARTITION BY store_name
           ORDER BY txn_seq
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
       ) AS running_revenue
FROM store_revenue
ORDER BY store_name, txn_seq;
